// Optional browser tests: install Playwright OUTSIDE the production dependency tree.
const { chromium } = require(process.env.WHATODO_PLAYWRIGHT_PATH || 'playwright')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const base = process.env.WHATODO_BROWSER_URL || 'http://127.0.0.1:3100'
if (!['localhost', '127.0.0.1'].includes(new URL(base).hostname)) throw Error('Browser tests only run on localhost')
const fixture = JSON.parse(fs.readFileSync(process.env.WHATODO_TEST_FIXTURE, 'utf8'))
const profile = fs.mkdtempSync(path.join(os.tmpdir(), 'whatodo-browser-'))
let context, page
const errors = []
async function launch() {
  context = await chromium.launchPersistentContext(profile, { headless: true, viewport: { width: 1440, height: 1000 }, serviceWorkers: 'block' })
  page = context.pages()[0]
  page.on('pageerror', e => errors.push(e.message))
  page.setDefaultTimeout(20000)
}
async function expectDashboard() { await page.getByRole('heading', { name: 'Dashboard', exact: true }).waitFor() }
async function nav(name) { await page.locator('aside nav').getByRole('button', { name: name === 'Notifications' ? /^Notifications(?:\s*\d+)?$/ : name, exact: true }).click() }
async function token() { return page.evaluate(() => localStorage.getItem('whatodo_token')) }
async function run() {
  await launch()
  await page.goto(base)
  await page.evaluate(({ owner, ws }) => { localStorage.setItem('whatodo_token', owner.token); localStorage.setItem('whatodo_workspace', ws.id) }, fixture)
  await page.reload(); await expectDashboard()
  assert.doesNotMatch(await page.locator('body').innerText(), /EPCO|Speed Dating|11 novembre 2026/i)
  await page.reload(); await expectDashboard(); assert.equal(await token(), fixture.owner.token)
  console.log('PASS reload restores a valid session; no legacy event shown')
  await context.close(); await launch(); await page.goto(base); await expectDashboard()
  assert.equal(await token(), fixture.owner.token)
  console.log('PASS actual browser closure/reopening retains localStorage session')

  await page.route('**/api/auth/me', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'Service temporairement indisponible' }) }))
  await page.reload(); await page.getByRole('button', { name: 'Réessayer' }).waitFor()
  assert.equal(await token(), fixture.owner.token)
  await page.unroute('**/api/auth/me'); await page.getByRole('button', { name: 'Réessayer' }).click(); await expectDashboard()
  console.log('PASS temporary API failure preserves token and retry restores session')

  await page.route('**/api/auth/me', async route => { await new Promise(resolve => setTimeout(resolve, 17000)); await route.abort().catch(() => {}) })
  await page.reload(); await page.getByText('Le serveur met trop de temps à répondre. Réessayez.', { exact: true }).waitFor({ timeout: 19000 })
  assert.equal(await token(), fixture.owner.token)
  await page.unroute('**/api/auth/me'); await page.getByRole('button', { name: 'Réessayer' }).click(); await expectDashboard()
  console.log('PASS 15-second timeout ends session loader without logout')

  await nav('Tous groupes'); await page.getByRole('button', { name: '+ Nouveau groupe', exact: true }).click()
  let dialog = page.getByRole('dialog')
  await dialog.getByLabel('Nom', { exact: true }).fill('Groupe navigateur')
  await dialog.getByLabel('Leader', { exact: true }).selectOption(fixture.member.user.id)
  await dialog.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await page.getByRole('heading', { name: 'Groupe navigateur', exact: true }).waitFor()
  let card = page.locator('div.surface').filter({ has: page.getByRole('heading', { name: 'Groupe navigateur', exact: true }) })
  await card.getByRole('button', { name: 'Modifier', exact: true }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByLabel('Nom', { exact: true }).fill('Groupe modifié')
  await dialog.getByLabel('Viewer', { exact: false }).check()
  await dialog.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await page.getByRole('heading', { name: 'Groupe modifié', exact: true }).waitFor()
  card = page.locator('div.surface').filter({ has: page.getByRole('heading', { name: 'Groupe modifié', exact: true }) })
  await card.getByRole('button', { name: 'Modifier', exact: true }).click()
  await page.getByRole('dialog').getByLabel('Viewer', { exact: false }).uncheck()
  await page.getByRole('dialog').getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await page.getByRole('dialog').waitFor({ state: 'hidden' })
  console.log('PASS group creation/editing, leader selection, member add/remove')

  await nav('Chat'); await page.getByRole('button', { name: '+ Nouveau salon', exact: true }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByLabel('Nom', { exact: true }).fill('Salon navigateur')
  await dialog.getByLabel('Type', { exact: true }).selectOption('private')
  await dialog.getByLabel('Member', { exact: false }).check()
  await dialog.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await page.getByRole('heading', { name: 'Salon navigateur', exact: true }).waitFor()
  await page.getByPlaceholder('Écrire dans #Salon navigateur…').fill('Message envoyé depuis le navigateur')
  await page.getByPlaceholder('Écrire dans #Salon navigateur…').press('Enter')
  await page.getByText('Message envoyé depuis le navigateur', { exact: true }).waitFor()
  page.once('dialog', d => d.accept()); await page.getByRole('button', { name: 'Archiver', exact: true }).click()
  await page.getByRole('button', { name: 'Réactiver', exact: true }).waitFor()
  assert.ok(await page.getByPlaceholder('Lecture seule', { exact: true }).isDisabled())
  await page.getByText('Message envoyé depuis le navigateur', { exact: true }).waitFor()
  console.log('PASS private channel creation, send message, archive retains history')

  await page.getByRole('button', { name: /Salon personnalisé/ }).click()
  await page.getByText('Message 249', { exact: true }).waitFor()
  await page.getByRole('button', { name: 'Messages précédents', exact: true }).click()
  await page.getByText('Message 0', { exact: true }).waitFor()
  console.log('PASS latest messages beyond 200 and older-message pagination')

  await nav('Tous groupes')
  card = page.locator('div.surface').filter({ has: page.getByRole('heading', { name: 'Groupe modifié', exact: true }) })
  page.once('dialog', d => d.accept()); await card.getByRole('button', { name: 'Supprimer', exact: true }).click()
  await page.getByRole('heading', { name: 'Groupe modifié', exact: true }).waitFor({ state: 'hidden' })
  console.log('PASS confirmed group deletion')

  // Views must show a retry, not spin forever on a failed read.
  for (const [view, endpoint] of [['Pilotage', '/pilot'], ['Calendrier', '/calendar**'], ['Gantt', '/tasks**'], ['Membres', '/workspace/members'], ['Notifications', '/notifications']]) {
    const pattern = '**/api' + endpoint
    await page.route(pattern, route => route.fulfill({ status: 500, contentType: 'application/json', body: JSON.stringify({ error: 'Erreur de test temporaire' }) }))
    await nav(view)
    // Notifications are polled; wait for its first request if hook was already mounted.
    await page.getByRole('button', { name: 'Réessayer', exact: true }).waitFor({ timeout: 19000 })
    await page.unroute(pattern); await page.getByRole('button', { name: 'Réessayer', exact: true }).click()
    await page.getByRole('alert').filter({ hasText: 'Erreur de test temporaire' }).waitFor({ state: 'hidden' })
  }
  console.log('PASS failed loaders recover: pilot, calendar, Gantt, members, notifications')
  await page.route('**/api/dashboard', route => route.fulfill({ status: 500, contentType: 'application/json', body: JSON.stringify({ error: 'Dashboard indisponible' }) }))
  await nav('Dashboard'); await page.getByRole('button', { name: 'Réessayer', exact: true }).waitFor()
  await page.unroute('**/api/dashboard'); await page.getByRole('button', { name: 'Réessayer', exact: true }).click(); await expectDashboard()
  await nav('Tous groupes')
  await page.route('**/api/groups/*', route => route.fulfill({ status: 500, contentType: 'application/json', body: JSON.stringify({ error: 'Groupe indisponible' }) }))
  await page.getByRole('heading', { name: 'Groupe renommé', exact: true }).click()
  await page.getByRole('button', { name: 'Réessayer', exact: true }).waitFor()
  await page.unroute('**/api/groups/*'); await page.getByRole('button', { name: 'Réessayer', exact: true }).click()
  await page.getByRole('heading', { name: 'Groupe renommé', exact: true }).waitFor()
  await page.route('**/api/groups', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'Groupes indisponibles' }) }))
  await page.reload(); await page.getByRole('button', { name: 'Réessayer', exact: true }).waitFor()
  assert.equal(await token(), fixture.owner.token)
  await page.unroute('**/api/groups'); await page.getByRole('button', { name: 'Réessayer', exact: true }).click(); await expectDashboard()
  console.log('PASS dashboard, group detail and initial group loading recover with retry')


  await page.getByRole('button', { name: 'Owner', exact: false }).last().click()
  await page.getByPlaceholder('Mot de passe actuel').fill(fixture.password)
  await page.getByPlaceholder('Nouveau mot de passe (8 caractères min.)').fill(fixture.password + 'browser')
  await page.getByPlaceholder('Confirmer le nouveau mot de passe').fill(fixture.password + 'browser')
  await page.getByRole('button', { name: 'Modifier le mot de passe', exact: true }).click()
  await page.waitForFunction(old => localStorage.getItem('whatodo_token') !== old, fixture.owner.token)
  await page.reload(); await expectDashboard()
  console.log('PASS password change stores renewed JWT; reload stays authenticated')

  await page.evaluate(({ viewer, ws }) => { localStorage.setItem('whatodo_token', viewer.token); localStorage.setItem('whatodo_workspace', ws.id) }, fixture)
  await page.reload(); await expectDashboard(); await nav('Chat')
  await page.getByPlaceholder('Lecture seule', { exact: true }).waitFor()
  assert.ok(await page.getByPlaceholder('Lecture seule', { exact: true }).isDisabled())
  assert.equal(await page.getByRole('button', { name: '+ Nouveau salon', exact: true }).count(), 0)
  console.log('PASS viewer chat is read-only')
  await page.route('**/api/auth/me', route => route.fulfill({ status: 401, contentType: 'application/json', body: JSON.stringify({ error: 'Non authentifié' }) }))
  await page.reload(); await page.getByRole('button', { name: 'Se connecter', exact: true }).waitFor()
  assert.equal(await token(), null)
  console.log('PASS genuine authentication 401 clears the session')
  await page.screenshot({ path: path.join(profile, 'whatodo-chat.png'), fullPage: true })
  assert.deepEqual(errors, [], 'No browser runtime errors')
  console.log('PASS no browser runtime errors')
}
run().catch(e => { console.error(e); process.exitCode = 1 }).finally(async () => { await context?.close() })
