const { test } = require('node:test')
const assert = require('node:assert/strict')
const { MongoClient } = require('mongodb')
const fs = require('node:fs')
const base = process.env.WHATODO_TEST_BASE_URL || 'http://127.0.0.1:3100/api'
const uri = process.env.WHATODO_TEST_MONGO_URL
if (!['localhost', '127.0.0.1'].includes(new URL(base).hostname) || !uri || !/^mongodb:\/\/(localhost|127\.0\.0\.1):/.test(uri)) throw Error('These mutating tests require an explicitly configured disposable LOCAL MongoDB and localhost API')
const password = 'Local-test-password-123'
async function api(path, user, workspace, method = 'GET', body, status = 200) {
  const res = await fetch(base + path, { method, headers: { 'Content-Type': 'application/json', ...(user ? { Authorization: `Bearer ${user.token}` } : {}), ...(workspace ? { 'X-Workspace-Id': workspace.id } : {}) }, body: body === undefined ? undefined : JSON.stringify(body), signal: AbortSignal.timeout(20000) })
  const value = await res.json()
  assert.equal(res.status, status, `${method} ${path}: ${JSON.stringify(value)}`)
  return value
}
test('production API with disposable MongoDB: product flows and authorization', async t => {
  const client = await MongoClient.connect(uri)
  const db = client.db('whatodo_test')
  t.after(() => client.close())
  const suffix = Date.now()
  const people = []
  for (const name of ['Owner', 'Admin', 'Member', 'Viewer', 'Outside']) people.push(await api('/auth/register', null, null, 'POST', { firstName: name, email: `${name.toLowerCase()}-${suffix}@example.test`, password }))
  const [owner, admin, member, viewer, outside] = people
  const ws = await api('/workspaces', owner, null, 'POST', { name: 'Workspace neuf' })
  const foreign = await api('/workspaces', outside, null, 'POST', { name: 'Autre espace' })
  for (const u of [admin, member, viewer]) await api('/workspaces/join', u, null, 'POST', { inviteCode: ws.inviteCode })
  const memberships = await api('/workspace/members', owner, ws)
  const membership = u => memberships.find(m => m.userId === u.user.id)
  await api(`/workspace/members/${membership(admin).id}`, owner, ws, 'PATCH', { role: 'admin' })
  await api(`/workspace/members/${membership(viewer).id}`, owner, ws, 'PATCH', { role: 'viewer' })
  let group, second, task, channel
  await t.test('new workspace is empty with two automatic channels', async () => {
    assert.equal((await api('/groups', owner, ws)).length, 0)
    assert.equal((await api('/tasks', owner, ws)).length, 0)
    assert.equal((await api('/channels', owner, ws)).length, 2)
  })
  await t.test('group creation, leader assignment, membership synchronization and editing', async () => {
    group = await api('/groups', owner, ws, 'POST', { name: 'Groupe Alpha', leaderId: member.user.id, memberIds: [member.user.id, viewer.user.id] })
    const detail = await api(`/groups/${group.id}`, member, ws)
    assert.equal(detail.leader.id, member.user.id)
    assert.equal(detail.members.length, 2)
    assert.equal((await db.collection('workspace_members').findOne({ userId: member.user.id, workspaceId: ws.id })).role, 'leader')
    await api(`/groups/${group.id}`, owner, ws, 'PATCH', { name: 'Groupe renommé', memberIds: [member.user.id], leaderId: member.user.id })
    assert.equal((await db.collection('workspace_members').findOne({ userId: viewer.user.id, workspaceId: ws.id })).groupId, null)
    second = await api('/groups', owner, ws, 'POST', { name: 'Groupe Beta', memberIds: [viewer.user.id] })
  })
  await t.test('foreign IDs rejected, group task confidentiality enforced', async () => {
    const fg = await api('/groups', outside, foreign, 'POST', { name: 'Privé autre espace' })
    await api('/groups', owner, ws, 'POST', { name: 'Invalid', memberIds: [outside.user.id] }, 400)
    await api('/groups', owner, ws, 'POST', { name: 'Invalid', leaderId: outside.user.id }, 400)
    await api(`/workspace/members/${membership(member).id}`, owner, ws, 'PATCH', { groupId: fg.id }, 404)
    await api(`/groups/${group.id}`, viewer, ws, 'GET', undefined, 403)
    await api('/tasks', owner, ws, 'POST', { groupId: fg.id, title: 'Invalid' }, 400)
    await api('/tasks', owner, ws, 'POST', { groupId: group.id, assignees: [outside.user.id], title: 'Invalid' }, 400)
  })
  await t.test('owner cannot be disabled/deleted by admin; inactive user loses access and cannot rejoin', async () => {
    await api(`/workspace/members/${membership(owner).id}`, admin, ws, 'PATCH', { status: 'inactive' }, 403)
    await api(`/workspace/members/${membership(owner).id}`, admin, ws, 'DELETE', undefined, 403)
    await api(`/workspace/members/${membership(owner).id}`, owner, ws, 'PATCH', { status: 'inactive' }, 400)
    await api(`/workspace/members/${membership(member).id}`, owner, ws, 'PATCH', { status: 'inactive' })
    await api('/tasks', member, ws, 'GET', undefined, 403)
    await api('/workspaces/join', member, null, 'POST', { inviteCode: ws.inviteCode }, 403)
    assert.equal((await db.collection('groups').findOne({ id: group.id })).leaderId, null)
    await api(`/workspace/members/${membership(member).id}`, owner, ws, 'PATCH', { status: 'active', role: 'member' })
  })
  await t.test('task validation, invalid payloads and direct done bypass blocked', async () => {
    task = await api('/tasks', owner, ws, 'POST', { title: 'Tâche test', groupId: group.id, assignees: [member.user.id], proofRequired: true })
    await api(`/tasks/${task.id}`, member, ws, 'PATCH', { status: 'done' }, 403)
    await api(`/tasks/${task.id}`, member, ws, 'PATCH', { status: 'unknown' }, 400)
    await api(`/tasks/${task.id}`, owner, ws, 'PATCH', { priority: 'unknown' }, 400)
    await api(`/tasks/${task.id}`, owner, ws, 'PATCH', { assignees: 'not-an-array' }, 400)
    await api(`/tasks/${task.id}`, owner, ws, 'PATCH', { groupId: { $ne: null } }, 400)
    await api(`/tasks/${task.id}/dates`, owner, ws, 'PATCH', { dueDate: 'invalid' }, 400)
    await api(`/tasks/${task.id}/dates`, owner, ws, 'PATCH', { dueDate: '2000-01-01' }, 400)
    await api(`/tasks/${task.id}`, member, ws, 'PATCH', { status: 'review' }, 400)
    await api(`/tasks/${task.id}/proofs`, member, ws, 'POST', { text: 'Travail terminé' })
    await api(`/tasks/${task.id}`, member, ws, 'PATCH', { status: 'review' })
    assert.equal((await api(`/tasks/${task.id}/validate`, owner, ws, 'POST', { approved: true })).status, 'done')
    await api(`/groups/${group.id}`, owner, ws, 'DELETE', undefined, 409)
  })
  await t.test('viewer is read only across tasks, comments, proofs, groups and chat', async () => {
    await api(`/workspace/members/${membership(viewer).id}`, owner, ws, 'PATCH', { groupId: group.id })
    await api(`/tasks/${task.id}`, owner, ws, 'PATCH', { assignees: [viewer.user.id, member.user.id] })
    await api(`/tasks/${task.id}`, viewer, ws)
    await api(`/tasks/${task.id}`, viewer, ws, 'PATCH', { status: 'in_progress' }, 403)
    await api(`/tasks/${task.id}`, viewer, ws, 'DELETE', undefined, 403)
    await api(`/tasks/${task.id}/comments`, viewer, ws, 'POST', { content: 'test' }, 403)
    await api(`/tasks/${task.id}/proofs`, viewer, ws, 'POST', { text: 'test' }, 403)
    await api('/tasks', viewer, ws, 'POST', { title: 'test', groupId: group.id }, 403)
    await api('/groups', viewer, ws, 'POST', { name: 'test' }, 403)
    const general = (await api('/channels', viewer, ws)).find(c => c.type === 'workspace')
    await api(`/channels/${general.id}/messages`, viewer, ws, 'POST', { content: 'test' }, 403)
  })
  await t.test('custom/private channels, latest 200 messages, older cursor and archive preservation', async () => {
    channel = await api('/channels', owner, ws, 'POST', { name: 'Salon personnalisé', type: 'workspace' })
    await api(`/channels/${channel.id}/messages`, member, ws, 'POST', { content: 'Bonjour' })
    const privateChannel = await api('/channels', owner, ws, 'POST', { name: 'Privé', type: 'private', memberIds: [member.user.id] })
    await api(`/channels/${privateChannel.id}/messages`, viewer, ws, 'GET', undefined, 403)
    const at = new Date()
    await db.collection('messages').insertMany(Array.from({ length: 250 }, (_, i) => ({ id: `message-${String(i).padStart(4, '0')}`, channelId: channel.id, workspaceId: ws.id, userId: owner.user.id, userName: 'Owner', content: `Message ${i}`, createdAt: at })))
    const latest = await api(`/channels/${channel.id}/messages`, member, ws)
    assert.equal(latest.length, 200); assert.equal(latest.at(-1).content, 'Message 249')
    const first = latest[0]
    const older = await api(`/channels/${channel.id}/messages?before=${encodeURIComponent(first.createdAt)}&beforeId=${first.id}`, member, ws)
    assert.equal(older.length, 51)
    assert.equal(new Set([...latest, ...older].map(m => m.id)).size, 251)
    await api(`/channels/${channel.id}`, owner, ws, 'PATCH', { archived: true })
    await api(`/channels/${channel.id}/messages`, owner, ws, 'POST', { content: 'No' }, 403)
    assert.equal(await db.collection('messages').countDocuments({ channelId: channel.id }), 251)
    await api(`/channels/${channel.id}`, owner, ws, 'PATCH', { archived: false })
  })
  await t.test('soft-deleted tasks cannot be read or mutated, but admins can restore', async () => {
    await api(`/tasks/${task.id}`, owner, ws, 'DELETE')
    await api(`/tasks/${task.id}`, member, ws, 'GET', undefined, 404)
    await api(`/tasks/${task.id}`, owner, ws, 'PATCH', { title: 'No' }, 404)
    await api(`/tasks/${task.id}/dates`, owner, ws, 'PATCH', { dueDate: '2027-01-01' }, 404)
    await api(`/tasks/${task.id}/restore`, owner, ws, 'POST')
  })
  await t.test('ungrouped tasks are not shared merely because both group IDs are null', async () => {
    await db.collection('tasks').insertOne({ id: 'ungrouped-private', workspaceId: ws.id, title: 'Privé', groupId: null, assignees: [owner.user.id], createdBy: owner.user.id })
    await api(`/workspace/members/${membership(member).id}`, owner, ws, 'PATCH', { groupId: null })
    await api('/tasks/ungrouped-private', member, ws, 'GET', undefined, 403)
    assert.ok(!(await api('/tasks', member, ws)).some(t => t.id === 'ungrouped-private'))
    assert.ok(!(await api('/calendar', member, ws)).some(t => t.id === 'ungrouped-private'))
  })
  await t.test('group removal cleans membership, archives channel and keeps messages', async () => {
    await api(`/groups/${second.id}`, owner, ws, 'PATCH', { memberIds: [member.user.id], leaderId: member.user.id })
    const gc = (await api('/channels', owner, ws)).find(c => c.groupId === second.id)
    await api(`/channels/${gc.id}/messages`, owner, ws, 'POST', { content: 'À conserver' })
    await api(`/groups/${second.id}`, owner, ws, 'DELETE')
    assert.equal((await db.collection('workspace_members').findOne({ userId: member.user.id, workspaceId: ws.id })).groupId, null)
    assert.ok((await db.collection('channels').findOne({ id: gc.id })).archivedAt)
    assert.equal(await db.collection('messages').countDocuments({ channelId: gc.id }), 1)
    await api(`/groups/${second.id}`, owner, ws, 'GET', undefined, 404)
  })
  await t.test('archived workspace read-only and can be unarchived', async () => {
    await api('/workspace/archive', owner, ws, 'POST')
    await api('/tasks', owner, ws)
    await api('/groups', owner, ws, 'POST', { name: 'No' }, 403)
    await api(`/tasks/${task.id}`, owner, ws, 'PATCH', { title: 'No' }, 403)
    await api('/workspace/unarchive', owner, ws, 'POST')
  })
  await t.test('password change and reset issue usable tokens and revoke old ones', async () => {
    const previous = { ...member }
    const result = await api('/auth/change-password', member, null, 'POST', { currentPassword: password, newPassword: password + 'x' })
    member.token = result.token
    await api('/auth/me', member)
    await api('/auth/me', previous, null, 'GET', undefined, 401)
    const resetToken = `reset-${suffix}`
    await db.collection('password_resets').insertOne({ id: resetToken, token: resetToken, userId: member.user.id, used: false, expiresAt: new Date(Date.now() + 60000) })
    const reset = await api('/auth/reset-password', null, null, 'POST', { token: resetToken, newPassword: password })
    await api('/auth/me', { token: reset.token })
    await api('/auth/me', member, null, 'GET', undefined, 401)
    member.token = reset.token
    await api('/auth/reset-password', null, null, 'POST', { token: resetToken, newPassword: password }, 400)
  })
  await t.test('donation declarations: validation, authorization, idempotency and private notifications', async () => {
    const payload = { firstName: 'Jean', lastName: 'Dupont', amount: '5', currency: 'CHF', requestId: require('node:crypto').randomUUID(), status: 'paid', userId: outside.user.id, workspaceId: foreign.id }
    const before = await db.collection('donations').countDocuments({})
    await api('/donations', null, ws, 'POST', payload, 401)
    await api('/donations', viewer, { id: 'missing' }, 'POST', payload, 403)
    await api('/donations', outside, ws, 'POST', payload, 403)
    for (const amount of [0, -1, 200.01, '1.234', 'abc', null, {}, '']) await api('/donations', viewer, ws, 'POST', { ...payload, amount }, 400)
    for (const change of [{ firstName: ' ' }, { lastName: '' }, { firstName: 'x'.repeat(81) }, { currency: 'EUR' }, { requestId: 'bad' }]) await api('/donations', viewer, ws, 'POST', { ...payload, ...change }, 400)
    assert.equal(await db.collection('donations').countDocuments({}), before)
    const responses = await Promise.all(Array.from({ length: 8 }, () => api('/donations', viewer, ws, 'POST', payload)))
    assert.equal(new Set(responses.map(r => r.id)).size, 1)
    assert.equal(responses[0].status, 'declared_paid')
    const donation = await db.collection('donations').findOne({ id: responses[0].id })
    assert.equal(donation.userId, viewer.user.id)
    assert.equal(donation.workspaceId, ws.id)
    assert.equal(donation.amount, 5)
    assert.equal(donation.currency, 'CHF')
    assert.ok(donation.createdAt instanceof Date)
    assert.equal(await db.collection('donations').countDocuments({}), before + 1)
    await api('/donations', viewer, ws, 'POST', { ...payload, amount: 10 }, 409)
    const notifications = await db.collection('notifications').find({ type: 'donation_declared', workspaceId: ws.id }).toArray()
    assert.equal(notifications.length, 2)
    assert.deepEqual(new Set(notifications.map(n => n.userId)), new Set([owner.user.id, admin.user.id]))
    const ownerNotification = notifications.find(n => n.userId === owner.user.id)
    await api('/notifications/mark-read', owner, ws, 'POST', { id: ownerNotification.id })
    assert.equal((await db.collection('notifications').findOne({ id: ownerNotification.id })).read, true)
    for (const bad of ['', null, {}, 'donation:bad:bad', 'missing:target']) await api('/notifications/mark-read', owner, ws, 'POST', { id: bad }, 400)
    const adminNotification = notifications.find(n => n.userId === admin.user.id)
    await api('/notifications/mark-read', viewer, ws, 'POST', { id: adminNotification.id })
    assert.equal((await db.collection('notifications').findOne({ id: adminNotification.id })).read, false)
    for (const n of notifications) {
      assert.equal(n.firstName, 'Jean'); assert.equal(n.lastName, 'Dupont'); assert.equal(n.amount, 5); assert.equal(n.currency, 'CHF')
      assert.match(n.body, /Jean Dupont indique avoir effectué un don de CHF 5.00/)
      assert.doesNotMatch(n.body, /4179|Paiement confirmé|Paiement reçu|Don vérifié/)
    }
    for (const u of [owner, admin]) assert.equal((await api('/notifications', u, ws)).filter(n => n.type === 'donation_declared').length, 1)
    assert.equal((await api('/notifications', viewer, ws)).filter(n => n.type === 'donation_declared').length, 0)
    await db.collection('workspace_members').updateOne({ id: membership(admin).id }, { $set: { role: 'member' } })
    assert.equal((await api('/notifications', admin, ws)).filter(n => n.type === 'donation_declared').length, 0)
    await db.collection('workspace_members').updateOne({ id: membership(admin).id }, { $set: { role: 'admin' } })
    // Retrying repairs missing notifications after a partial failure without duplicating the donation.
    await db.collection('notifications').deleteOne({ _id: notifications[0]._id })
    await api('/donations', viewer, ws, 'POST', payload)
    assert.equal(await db.collection('notifications').countDocuments({ type: 'donation_declared', workspaceId: ws.id }), 2)
    assert.equal(await db.collection('donations').countDocuments({}), before + 1)
    await api('/donations', viewer, ws, 'POST', { ...payload, requestId: require('node:crypto').randomUUID(), amount: 200 })
    await api('/workspace/archive', owner, ws, 'POST')
    await api('/donations', viewer, ws, 'POST', { ...payload, requestId: require('node:crypto').randomUUID() }, 403)
    await api('/workspace/unarchive', owner, ws, 'POST')
  })
  // Fixture for the optional browser smoke test. Contains ONLY fresh disposable local credentials.
  if (process.env.WHATODO_TEST_FIXTURE) fs.writeFileSync(process.env.WHATODO_TEST_FIXTURE, JSON.stringify({ owner, member, viewer, ws, password }))
})
